-- +goose Up
-- SQL in this section is executed when the migration is applied.
CREATE TABLE IF NOT EXISTS remit_to_acc_history (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    org_id uuid NOT NULL,
    partner text DEFAULT '',
    reference_number text DEFAULT '',
    trx_date timestamptz NOT NULL,
    account_number text DEFAULT '',
    currency text DEFAULT '',
    service_charge text DEFAULT '',
    remarks text DEFAULT '',
    particulars text DEFAULT '',
    merchant_name text DEFAULT '',
    bank_id INT NOT NULL,
    location_id INT NOT NULL,
    user_id INT NOT NULL,
    currency_id text DEFAULT '',
    customer_id text DEFAULT '',
    form_type text DEFAULT '',
    form_number text DEFAULT '',
    trx_type text DEFAULT '',
    remote_location_id INT NOT NULL,
    remote_user_id INT NOT NULL,
    biller_name text DEFAULT '',
    trx_time text DEFAULT '',
    total_amount text DEFAULT '0',
    account_name text DEFAULT '',
    beneficiary_address text DEFAULT '',
    beneficiary_birthdate text DEFAULT '',
    beneficiary_city text DEFAULT '',
    beneficiary_civil text DEFAULT '',
    beneficiary_country text DEFAULT '',
    beneficiary_customertype text DEFAULT '',
    beneficiary_firstname text DEFAULT '',
    beneficiary_lastname text DEFAULT '',
    beneficiary_middlename text DEFAULT '',
    beneficiary_tin text DEFAULT '',
    beneficiary_sex text DEFAULT '',
    beneficiary_state text DEFAULT '',
    currency_code_principal_amount text DEFAULT '0',
    principal_amount text DEFAULT '0',
    record_type text DEFAULT '',
    remitter_address text DEFAULT '',
    remitter_birthdate text DEFAULT '',
    remitter_city text DEFAULT '',
    remitter_civil text DEFAULT '',
    remitter_country text DEFAULT '',
    remitter_customer_type text DEFAULT '',
    remitter_firstname text DEFAULT '',
    remitter_gender text DEFAULT '',
    remitter_id INT NOT NULL,
    remitter_lastname text DEFAULT '',
    remitter_middlename text DEFAULT '',
    remitter_state text DEFAULT '',
    settlement_mode text DEFAULT '',
    notification boolean DEFAULT 'false',
    bene_zip_code text DEFAULT '',
    info jsonb DEFAULT '{}',
    details jsonb DEFAULT '{}',
    txn_status text DEFAULT '',
    error_code text DEFAULT '',
    error_message text DEFAULT '',
    error_time text DEFAULT '',
    error_type text DEFAULT '',
    updated_by  text DEFAULT '',
    created_by text DEFAULT '',
	created timestamptz NOT NULL DEFAULT NOW(),
    updated timestamptz NOT NULL DEFAULT NOW()
);

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.
DROP TABLE IF EXISTS remit_to_acc_history;
