#!/usr/bin/env bash

set -e -x

if ! helm version | grep -q '"v3\.'; then
	echo "Please install helm 3.0"
	exit 1
fi

helm repo add ory https://k8s.ory.sh/helm/charts
helm repo update

helm upgrade --namespace cebuana-corporate \
        --debug \
        --atomic \
        --version 0.6.1 \
        --install hydra ory/hydra \
        -f helm-values/hydra.yaml \
        -f helm-values/hydra-project.yaml

helm upgrade --namespace cebuana-corporate \
        --debug \
        --atomic \
        --version 0.6.1 \
        --install keto ory/keto \
        -f helm-values/keto.yaml \
        -f helm-values/keto-project.yaml
