apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
data:
  TZ: "Asia/Manila"
  RUNTIME_ENVIRONMENT: "DEPLOY_ENV"
  SERVER_HOST: "OVERLAY_ME"
  INFLUXDB_HOST: influxdb2.influxdb.svc.cluster.local
  INFLUXDB_PORT: '8086'
  INFLUXDB_BATCHSIZE: '100'
  INFLUXDB_GRPCMEASURE: profile_grpc_latency
  INFLUXDB_HTTPMEASURE: profile_http_latency
