apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    app.kubernetes.io/instance: profile
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: profile
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: profile
    spec:
      containers:
      - name: profile
        image: profile:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        envFrom:
        - configMapRef:
            name: profile-config
        - secretRef:
            name: profile-secret
        - secretRef:
            name: smtp-secret
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
