apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml

commonLabels:
  app.kubernetes.io/name: profile
  app.kubernetes.io/part-of: petnet-drp
  app.kubernetes.io/component: profile 

