apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: petnet-uat

patchesStrategicMerge:
- config.yaml

patchesJson6902:
- path: ingress.yaml
  target:
    group: extensions
    kind: Ingress
    name: dsa-sim
    version: v1beta1
