apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
data:
  RUNTIME_ENVIRONMENT: staging
  DATABASE_HOST: 172.30.225.19
  DATABASE_DBNAME: profiledb_dev
  USERMGM_API: usermgm:80
  USERMGM_ADMIN: usermgm-admin:80
  AUTH_URL: https://auth.staging.petnet.dev
  USERMGM_MOCK: "false"
  CMS_URL: https://staging.petnet.dev
  INFLUXDB_BUCKET: conexdev
  INFLUXDB_ORGANIZATION: petnetdev
  HYDRA_ADMINURL: http://hydra-admin
  HYDRA_AUDIENCE: https://staging.petnet.dev
  TRACE_COLLECTORHOST: my-opentelemetry-collector.tracing.svc.cluster.local:4317
