---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  RUNTIME_LOGLEVEL: debug
  RUNTIME_ENVIRONMENT: live
  DATABASE_HOST: 172.30.225.19
  DATABASE_DBNAME: petnetdb_uat
  CORS_ORIGINS: "https://api.uat.petnet.dev,https://*.api.uat.petnet.dev"
  HYDRA_ADMINURL: http://hydra-admin
  HYDRA_AUDIENCE: https://api.uat.petnet.dev
  AUTH_OAUTHURL: https://auth.uat.petnet.dev
  AUTH_ISSUER: https://auth.uat.petnet.dev
  AUTH_TOKEN: https://auth.uat.petnet.dev/oauth2/token
  AUTH_COOKIEMAXAGE: "43200"
  PERAHUB_BASEURL: https://newkycgateway.dev.perahub.com.ph/gateway/
  PERAHUB_SERVERIP: 34.87.153.43
  PERAHUB_AUTHMOCK: "false"
  PERAHUB_TIMEOUT: 45s
  INFLUXDB_BUCKET: conexuat
  INFLUXDB_ORGANIZATION: petnetdev

...
