apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml
- ingress.yaml
- leaderconfig.yaml
- rbac.yaml

commonLabels:
  app.kubernetes.io/name: brankas-rbac
  app.kubernetes.io/part-of: brankas-rbac
  app.kubernetes.io/component: idp

images:
- name: leaderelex
  newName: asia.gcr.io/o-production/leaderelex
  newTag: v3.8.3.0

replacements:
- source:
    kind: ServiceAccount
    name: leader
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: ClusterRoleBinding
      name: leader-role
    fieldPaths:
    - subjects.[name=leader].namespace
