---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: leader

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-role
subjects:
- kind: ServiceAccount
  name: leader
  namespace: NAMESPACE
roleRef:
  kind: ClusterRole
  name: leader-role
  apiGroup: rbac.authorization.k8s.io

...
