// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package quote

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteServiceClient interface {
	// Get a quote for choosen remit partner.
	QuoteInquiry(ctx context.Context, in *QuoteInquiryRequest, opts ...grpc.CallOption) (*QuoteInquiryResponse, error)
	// Get quote requirements for making a transaction.
	QuoteRequirements(ctx context.Context, in *QuoteRequirementsRequest, opts ...grpc.CallOption) (*QuoteRequirementsResponse, error)
	// Create quote for making a transaction.
	CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*CreateQuoteResponse, error)
}

type quoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteServiceClient(cc grpc.ClientConnInterface) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) QuoteInquiry(ctx context.Context, in *QuoteInquiryRequest, opts ...grpc.CallOption) (*QuoteInquiryResponse, error) {
	out := new(QuoteInquiryResponse)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/QuoteInquiry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) QuoteRequirements(ctx context.Context, in *QuoteRequirementsRequest, opts ...grpc.CallOption) (*QuoteRequirementsResponse, error) {
	out := new(QuoteRequirementsResponse)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/QuoteRequirements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*CreateQuoteResponse, error) {
	out := new(CreateQuoteResponse)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/CreateQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
// All implementations must embed UnimplementedQuoteServiceServer
// for forward compatibility
type QuoteServiceServer interface {
	// Get a quote for choosen remit partner.
	QuoteInquiry(context.Context, *QuoteInquiryRequest) (*QuoteInquiryResponse, error)
	// Get quote requirements for making a transaction.
	QuoteRequirements(context.Context, *QuoteRequirementsRequest) (*QuoteRequirementsResponse, error)
	// Create quote for making a transaction.
	CreateQuote(context.Context, *CreateQuoteRequest) (*CreateQuoteResponse, error)
	mustEmbedUnimplementedQuoteServiceServer()
}

// UnimplementedQuoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuoteServiceServer struct{}

func (UnimplementedQuoteServiceServer) QuoteInquiry(context.Context, *QuoteInquiryRequest) (*QuoteInquiryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteInquiry not implemented")
}

func (UnimplementedQuoteServiceServer) QuoteRequirements(context.Context, *QuoteRequirementsRequest) (*QuoteRequirementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteRequirements not implemented")
}

func (UnimplementedQuoteServiceServer) CreateQuote(context.Context, *CreateQuoteRequest) (*CreateQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) mustEmbedUnimplementedQuoteServiceServer() {}

// UnsafeQuoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteServiceServer will
// result in compilation errors.
type UnsafeQuoteServiceServer interface {
	mustEmbedUnimplementedQuoteServiceServer()
}

func RegisterQuoteServiceServer(s grpc.ServiceRegistrar, srv QuoteServiceServer) {
	s.RegisterService(&QuoteService_ServiceDesc, srv)
}

func _QuoteService_QuoteInquiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).QuoteInquiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/QuoteInquiry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).QuoteInquiry(ctx, req.(*QuoteInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_QuoteRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequirementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).QuoteRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/QuoteRequirements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).QuoteRequirements(ctx, req.(*QuoteRequirementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_CreateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/CreateQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateQuote(ctx, req.(*CreateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteService_ServiceDesc is the grpc.ServiceDesc for QuoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quote.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuoteInquiry",
			Handler:    _QuoteService_QuoteInquiry_Handler,
		},
		{
			MethodName: "QuoteRequirements",
			Handler:    _QuoteService_QuoteRequirements_Handler,
		},
		{
			MethodName: "CreateQuote",
			Handler:    _QuoteService_CreateQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brank.as/petnet/gunk/drp/v1/quote/all.proto",
}
