apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgm
  labels:
    app.kubernetes.io/instance: usermgm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: usermgm
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: usermgm
    spec:
      containers:
      - name: usermgm
        image: rbac/usermgm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: usermgm-config
        - secretRef:
            name: usermgm-secret
        - secretRef:
            name: smtp-secret
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
