apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml

commonLabels:
  app.kubernetes.io/name: brankas-rbac
  app.kubernetes.io/part-of: brankas-rbac
  app.kubernetes.io/component: usermgm
