apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-real
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@brank.as
    privateKeySecretRef:
      name: letsencrypt-real
    solvers:
    - http01:
        ingress:
          class: traefik
