apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-deploy-env
data:
  ENV: "production"
  HOST: "sso.proxtera.com"
  CORS_ORIGINS: "*.proxtera.com"
  GOOGLE_CALLBACK: "https://sso.proxtera.com/login/google-callback"
  SITE_URL: https://account.proxtera.com
  BASE_URL: https://account.proxtera.com
  PROXTERA_URL: https://account.proxtera.com
  SIGNUP_URL: https://account.proxtera.com
  AMD_URL: https://account.proxtera.com
  USER_MGM_URL: https://usermgm.proxtera.com

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
data:
  SERVE_TLS_ALLOW_TERMINATION_FROM: "10.0.0.0/14,192.168.0.0/16"
  URLS_SELF_ISSUER: "https://sso.proxtera.com/"
  URLS_CONSENT: "https://sso.proxtera.com/consent"
  URLS_LOGIN: "https://sso.proxtera.com/login"
  URLS_LOGOUT: "https://sso.proxtera.com/logout"
  CORS_ALLOWED_ORIGINS: "https://account.proxtera.com,https://*.proxtera.com,*.proxtera.com"
  #default redirect when nothing specified is to home
  URLS_POST_LOGOUT_REDIRECT: "https://account.proxtera.com/"

...
