#!/bin/sh

if [ -n "$VERSION" ]; then
	: # nothing to do
elif [ -f .version ]; then
	VERSION=$(cat .version)
elif command -v git-buildnumber >/dev/null; then
	VERSION=$(git-buildnumber)
else
	echo "need \$VERSION, git-buildnumber, or a .version file"
	exit 1
fi

if [ -n "$DRONE_COMMIT_SHA" ]; then
	: # nothing to do
elif command -v git >/dev/null; then
	DRONE_COMMIT_SHA=$(git rev-parse HEAD)
else
	echo "need \$DRONE_COMMIT_SHA, or git"
	exit 1
fi

SHORT_SHA=$(echo $DRONE_COMMIT_SHA | cut -c-4)
echo ${VERSION}-${SHORT_SHA}
