apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: proxtera-production

patchesStrategicMerge:
- config_patch.yaml

images:
- name: proxtera-production/usermgm
  newName: 461111061869.dkr.ecr.ap-southeast-1.amazonaws.com/proxtera-production/usermgm
  newTag: v0.11.5.10-412e
